### ISSUE TITLE
Any possible way we could get this updated to use Playwright 1.30.0?

### ISSUE THREAD

**Issue by bthompzon** [bgotink/playwright-coverage#15]
Hi there,
First off this library is awesome so thx for your efforts. I'm wondering if it could be updated to point to latest playwright version 1.30.0 -> https://github.com/microsoft/playwright/releases/tag/v1.30.0

Thanks

**Comment by bgotink** [comment]
Is it necessary to update the library on my end? Playwright is listed as peer dependency, so you should be in full control over the actual version that's used.
Unless relevant (breaking) changes were made to the APIs this package uses of course&hellip;

**Comment by bthompzon** [comment]
Actually I don't believe it is now that we have been playing with this. Ok well thanks again for the quick reply. :)

**Comment by bthompzon** [comment]
@bgotink I think actually some of the changes specifically with Test and Expect might not be available without it being updated.

**Comment by bgotink** [comment]
This package doesn't decide the version of `@playwright/test` though.

I know npm made the questionable decision in v7 to auto-install peer dependencies which makes it look like this package is managing the version if you're using npm, but that's not the case.

You can add any version of `@playwright/test` to your package.json—or at least any version allowed by the peer dependency range, so `^1.14.1`—and this package will automatically use that version.
