### ISSUE TITLE
Hidden source Map

### ISSUE THREAD

**Issue by mvolkert** [bgotink/playwright-coverage#9]
Is there a way to get coverage working with the hidden source map feature of angular ?
`"sourceMap": {
  "hidden": true,
  "scripts": true,
  "styles": true
}`
In that case the browser does not know about the source map, but it could be attached. 
Is there a way to attach the source map via playwright or your extension ?

**Comment by bgotink** [comment]
Turned out to be easy to implement, at least for the case where the sourcemap is served is served as URL + ".map". That means `ng serve` with hidden source maps works out of the box.

I'm not sure how easy it would be to make this more configurable, e.g. allowing to attach source maps from a folder or another URL entirely.

**Comment by mvolkert** [comment]
Thank you very much for this quick feature addition :)
I will test it as soon it's available via npm.

**Comment by bgotink** [comment]
Ah, I should've mentioned this is testable in 0.1.4 :)

**Comment by stovmascript** [comment]
I've installed from main (92e9fb6e3e60daf7323dda5e7e19b5852dece819), but am still getting some error, which looks related to source maps:

![image](https://user-images.githubusercontent.com/14262802/183694758-793fd26d-cc36-4449-bac8-602b35048c35.png)

It fails parsing the source map at https://github.com/bgotink/playwright-coverage/blob/main/src/data.ts#L67.

We're using Next.js and setting `productionBrowserSourceMaps: true` as described here: https://nextjs.org/docs/advanced-features/source-maps. I'm not sure which webpack `devtool` it's setting, but the `.map` files are on disk and available when requested.

**Comment by stovmascript** [comment]
Oops, it's this line https://github.com/bgotink/playwright-coverage/blob/main/src/data.ts#L92

**Comment by stovmascript** [comment]
Logged the `resolved` object, and looks like it's trying to fetch a source map for a 3rd party resource: `https://cdn.productboard.com/assets/portal-e461af7007938b26bd05.js.map`.

**Comment by bgotink** [comment]
Oh yeah, I hadn't considered that third parties might have scripts that include the `sourceMappingURL` footer but don't actually expose the sourcemap&hellip; Thanks!
